<a href="https://colab.research.google.com/github/anirbrhm/Deep-Learning/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loading the Data 

In [2]:
import sklearn.datasets 
import numpy as np 

Breast Cancer Data Set :

Documentation - https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_breast_cancer.html

In [3]:
X,Y = sklearn.datasets.load_breast_cancer(return_X_y = True) 
# these are returned as numpy arrays 

In [4]:
print(X.shape[0], X.shape[1])
print(Y.shape[0])

569 30
569


In [5]:
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [6]:
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [7]:
import pandas as pd 

In [8]:
# converting the numpy array into a data frame to visualize the data better 
X = pd.DataFrame(X,columns=sklearn.datasets.load_breast_cancer().feature_names) # just adding the column names to understand the data better 

In [9]:
X.head() 

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [10]:
X_Y = X.assign(Y = Y) # creating a new data frame to be able to visulaize the values with the outputs 

In [11]:
X_Y

mean radius  mean texture  ...  worst fractal dimension  Y
0          17.99         10.38  ...                  0.11890  0
1          20.57         17.77  ...                  0.08902  0
2          19.69         21.25  ...                  0.08758  0
3          11.42         20.38  ...                  0.17300  0
4          20.29         14.34  ...                  0.07678  0
..           ...           ...  ...                      ... ..
564        21.56         22.39  ...                  0.07115  0
565        20.13         28.25  ...                  0.06637  0
566        16.60         28.08  ...                  0.07820  0
567        20.60         29.33  ...                  0.12400  0
568         7.76         24.54  ...                  0.07039  1

[569 rows x 31 columns]

In [12]:
X_Y.describe() # describing the data

mean radius  mean texture  ...  worst fractal dimension           Y
count   569.000000    569.000000  ...               569.000000  569.000000
mean     14.127292     19.289649  ...                 0.083946    0.627417
std       3.524049      4.301036  ...                 0.018061    0.483918
min       6.981000      9.710000  ...                 0.055040    0.000000
25%      11.700000     16.170000  ...                 0.071460    0.000000
50%      13.370000     18.840000  ...                 0.080040    1.000000
75%      15.780000     21.800000  ...                 0.092080    1.000000
max      28.110000     39.280000  ...                 0.207500    1.000000

[8 rows x 31 columns]

In [13]:
print(X_Y["Y"].value_counts())

1    357
0    212
Name: Y, dtype: int64


In [14]:
print(sklearn.datasets.load_breast_cancer().target_names)

['malignant' 'benign']


In [16]:
X_Y.groupby("Y").mean() # shows the values of the features less for 1 than for 0 on average. 

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
Y                             ...                                         
0    17.462830     21.604906  ...        0.323468                 0.091530
1    12.146524     17.914762  ...        0.270246                 0.079442

[2 rows x 30 columns]

# Train Test Split

In [17]:
from sklearn.model_selection import train_test_split 

In [22]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.1,stratify=Y,random_state=1) # random state is very important for ML problem. 

In [23]:
print(X.shape,X_train.shape,X_test.shape)

(569, 30) (512, 30) (57, 30)


In [24]:
print(Y.mean(),Y_train.mean(),Y_test.mean()) # stratify ensures that the means are near about equal

0.6274165202108963 0.626953125 0.631578947368421


# Binarisation 

In [28]:
X_Y

mean radius  mean texture  ...  worst fractal dimension  Y
0          17.99         10.38  ...                  0.11890  0
1          20.57         17.77  ...                  0.08902  0
2          19.69         21.25  ...                  0.08758  0
3          11.42         20.38  ...                  0.17300  0
4          20.29         14.34  ...                  0.07678  0
..           ...           ...  ...                      ... ..
564        21.56         22.39  ...                  0.07115  0
565        20.13         28.25  ...                  0.06637  0
566        16.60         28.08  ...                  0.07820  0
567        20.60         29.33  ...                  0.12400  0
568         7.76         24.54  ...                  0.07039  1

[569 rows x 31 columns]

In [30]:
# manual binarisation 
X_binarised_3_train = X_train["mean area"].map(lambda x : 0 if x<100 else 1) 
X_binarised_3_train.head()

430    1
48     1
105    1
467    1
547    1
Name: mean area, dtype: int64

In [32]:
# as all the values for 1 is less than the values for 0 
X_binarised_train = X_train.apply(pd.cut,bins=2,labels=[1,0])
X_binarised_test = X_test.apply(pd.cut,bins=2,labels=[1,0]) 

In [39]:
X_binarised_train = X_binarised_train.values
X_binarised_test = X_binarised_test.values

In [40]:
print(type(X_binarised_train),type(Y_train))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
